---
- name: Install web server
  ansible.builtin.apt:
    name: apache2
    state: present
  when: install_apache | default(false)
  tags: [apache]

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  when: install_nginx | default(false)
  tags:
    - nginx

- name: Configure Nginx proxy for Apache
  ansible.builtin.include_tasks: nginx_proxy_apache.yml
  when: nginx_proxy_apache | default(false)
  tags:
    - proxy
