---
- name: Install web server
  ansible.builtin.apt:
    name: apache2
    state: present
    when: install_apache | default(false)


- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    when: install_nginx | default(false)

- name: Configure Apache port
  ansible.builtin.template:
    src: apache/ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: "0644"
  when: install_apache and nginx_proxy_apache
  notify: restart apache

- name: Make nginx reverse proxy for Apache
  ansible.builtin.template:
    src: nginx/default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  when: nginx_proxy_apache | default(false)
  notify: restart nginx

- name: Enable nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  when: nginx_proxy_apache | default(false)
  notify: restart nginx