- name: Install MariaDB
  ansible.builtin.include_tasks: mariadb.yml
  when: mariadb | default(false)
  tags: [mariadb]

- name: Install PostgreSQL
  ansible.builtin.include_tasks: postgresql.yml
  when: postgres | default(false)
  tags: [postgres]