---
- name: Install MariaDB packages
  ansible.builtin.package:
    - mariadb-server
    - mariadb-client
    - python3-pymysql

- name: Start and enable MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true