---
- name: Create Joomla installation directory
  ansible.builtin.file:
    path: /var/www/joomla/
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Check if Joomla is already downloaded
  ansible.builtin.stat:
    path: /var/www/joomla/index.php
  register: joomla_downloaded

- name: Download and extract Joomla
  ansible.builtin.unarchive:
    src: https://downloads.joomla.org/cms/joomla6/6-0-1/Joomla_6-0-1-Stable-Full_Package.zip
    dest: /var/www/joomla/
    remote_src: yes
    owner: www-data
    group: www-data
  when: not joomla_downloaded.stat.exists
