---
- name: restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: restart php-fpm
  ansible.builtin.service:
    name: php-{{ php_version }}-fpm
    state: restarted
