---
- name: restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  when: apache_installed is defined and apache_installed.stat.exists

- name: restart php-fpm
  ansible.builtin.service:
    name: php-{{ php_version }}-fpm
    state: restarted
